const $=id=>document.getElementById(id), poster=$('poster');
const genres=[['romance','♡ ROMANCE'],['youth','✿ YOUTH'],['romcom','♡ ROM-COM'],['thriller','☾ THRILLER'],['horror','◼ HORROR'],['sf','✦ SF'],['fantasy','☁ FANTASY'],['period','♛ PERIOD'],['indie','🎞 INDIE']];
const colorList=[['pink','#bd7893'],['cream','#c5ad91'],['sky','#7296ad'],['lavender','#887da6'],['wine','#6c273d'],['navy','#17283c'],['mono','#555'],['black','#111']];let genre='romance',color='pink';
function makeChips(){genres.forEach(([v,n],i)=>{let b=document.createElement('button');b.textContent=n;b.className=i?'':'on';b.onclick=()=>{genre=v;document.querySelectorAll('#genres button').forEach(x=>x.classList.remove('on'));b.classList.add('on');render()};$('genres').append(b)});colorList.forEach(([v,c],i)=>{let b=document.createElement('button');b.style.background=c;b.title=v;b.className=i?'':'on';b.onclick=()=>{color=v;document.querySelectorAll('#colors button').forEach(x=>x.classList.remove('on'));b.classList.add('on');render()};$('colors').append(b)})}makeChips();
const ids=['title','subtitle','tagline','star1','star2','date','runtime','synopsis','director','writer','music','layout','format','align','festival'];ids.forEach(id=>$(id).addEventListener('input',render));
function render(){poster.className=`poster genre-${genre} color-${color} layout-${$('layout').value} align-${$('align').value} ${$('format').value==='social'?'social':$('format').value==='a4'?'a4':''}`;$('pTitle').textContent=$('title').value||'UNTITLED';$('pSub').textContent=$('subtitle').value;$('pTag').textContent=$('tagline').value;$('pStars').textContent=[$('star1').value,$('star2').value].filter(Boolean).join(' · ');$('pSyn').textContent=$('synopsis').value;let d=$('date').value?$('date').value.replaceAll('-','.'):'COMING SOON';$('pMeta').textContent=`${genre.toUpperCase()} · ${d} · ${$('runtime').value}`;$('pCredits').innerHTML=`DIRECTED BY <b>${esc($('director').value)}</b> · WRITTEN BY <b>${esc($('writer').value)}</b> · MUSIC BY <b>${esc($('music').value)}</b>`;$('fest').style.display=$('festival').checked?'block':'none';fit()}function esc(s){let d=document.createElement('div');d.textContent=s;return d.innerHTML}
function fit(){if(innerWidth>620){poster.style.transform='';poster.parentElement.style.height='';return}poster.style.transform='';let w=poster.getBoundingClientRect().width,avail=$('stage').clientWidth,scale=Math.min(1,avail/w);poster.style.transform=`scale(${scale})`;poster.parentElement.style.height=(poster.offsetHeight*scale)+'px'}addEventListener('resize',fit);
let cropTarget=null,cropImage=new Image(),cx=0,cy=0,baseScale=1,zoom=1,drag=false,lx=0,ly=0;const cc=$('cropCanvas'),ctx=cc.getContext('2d');function drawCrop(){ctx.clearRect(0,0,700,700);let s=baseScale*zoom,w=cropImage.naturalWidth*s,h=cropImage.naturalHeight*s;ctx.drawImage(cropImage,cx+(700-w)/2,cy+(700-h)/2,w,h)}function openCrop(file,target,nameEl){let r=new FileReader();r.onload=e=>{cropImage=new Image();cropImage.onload=()=>{cropTarget={target,nameEl,file};baseScale=Math.max(700/cropImage.naturalWidth,700/cropImage.naturalHeight);zoom=1;cx=cy=0;$('zoom').value=1;$('cropModal').classList.add('open');drawCrop()};cropImage.src=e.target.result};r.readAsDataURL(file)}
function photo(id,img,name){$(id).onchange=()=>{let f=$(id).files[0];if(f)openCrop(f,$(img),$(name));$(id).value=''}}photo('photo1','img1','name1');photo('photo2','img2','name2');$('zoom').oninput=()=>{zoom=+$('zoom').value;drawCrop()};cc.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;cc.setPointerCapture(e.pointerId)};cc.onpointermove=e=>{if(!drag)return;let rect=cc.getBoundingClientRect(),ratio=700/rect.width;cx+=(e.clientX-lx)*ratio;cy+=(e.clientY-ly)*ratio;lx=e.clientX;ly=e.clientY;drawCrop()};cc.onpointerup=()=>drag=false;$('cropReset').onclick=()=>{cx=cy=0;zoom=1;$('zoom').value=1;drawCrop()};$('cropClose').onclick=()=>{$('cropModal').classList.remove('open');cropTarget=null};$('cropApply').onclick=()=>{if(!cropTarget)return;cropTarget.target.src=cc.toDataURL('image/jpeg',.94);cropTarget.target.style.display='block';cropTarget.nameEl.textContent=cropTarget.file.name;$('cropModal').classList.remove('open');cropTarget=null;render()};
const samples=[['MOONLIT','A LOVE FOUND AFTER MIDNIGHT','Even the longest night ends with you.','SEO YUN','HAN SOL'],['SUMMER, AGAIN','WE WERE YOUNG ONCE','I remember the summer by your name.','JI WOO','HA NEUL'],['AFTERIMAGE','NOTHING DISAPPEARS COMPLETELY','Every secret leaves a shadow.','MIN','JAE']];$('sample').onclick=()=>{let s=samples[Math.floor(Math.random()*samples.length)];['title','subtitle','tagline','star1','star2'].forEach((id,i)=>$(id).value=s[i]);$('synopsis').value='평범한 하루라고 생각했던 순간이 오래도록 잊히지 않을 한 장면이 된다. 두 사람의 이야기는 아직 끝나지 않았다.';render()};$('reset').onclick=()=>{location.reload()};
$('save').onclick=async()=>{if(!window.html2canvas){alert('저장 모듈을 불러오지 못했어요.');return}let btn=$('save'),old=btn.textContent;btn.textContent='포스터 만드는 중…';btn.disabled=true;try{if(document.fonts)await document.fonts.ready;for(const im of poster.querySelectorAll('img'))if(im.src)try{await im.decode()}catch{}let root=document.createElement('div');root.className='dearly-export';let clone=poster.cloneNode(true);clone.style.transform='none';root.append(clone);document.body.append(root);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));let canvas=await html2canvas(clone,{scale:3,useCORS:true,backgroundColor:null,logging:false,width:clone.offsetWidth,height:clone.offsetHeight,windowWidth:1400,windowHeight:1800});root.remove();canvas.toBlob(blob=>{let a=document.createElement('a'),url=URL.createObjectURL(blob),name=($('title').value||'Movie').replace(/[\\/:*?"<>|]/g,' ');a.href=url;a.download=`DEARLY FILM — ${name}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')}catch(e){console.error(e);alert('PNG 저장 중 문제가 생겼어요.')}finally{btn.textContent=old;btn.disabled=false}};render();
